### ISSUE TITLE
Allow user to specify the paths to dependencies

### ISSUE THREAD

**Issue by jfwalker** [FePhyFoFum/PyPHLAWD#10]
Right now the dependencies are hard coded in the scripts to look for them in the users bin, would be helpful to allow users to specify where the dependencies are located in the conf file.

**Comment by josephwb** [comment]
Doesn't it just expect things to be in the PATH? I cannot find an explicit mention of `bin`.

**Comment by jfwalker** [comment]
Yeah, sorry I meant PATH.

**Comment by blackrim** [comment]
Does this need to be updated? I would expect things to be in the PATH but we could let people know how to do that
