### ISSUE TITLE
Monotypic taxa

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/PyPHLAWD#13]
e.g. an Order with a single family. Two issues:
1. constraint tree from `find_good_clusters_for_concat.py` includes root edge, which RAxML barfs on. would be nice to not write these. probably will involve internal knuckles as well. `pxcltr` can remove these but would be nice to not have to bother.
2. again using `find_good_clusters_for_concat.py` I get different numbers of default clusters depending on if I run it from the top directory (e.g., 3) or down one (e.g., 1). this doesn't make sense as no new taxa are added moving to the top directory.

**Comment by blackrim** [comment]
Can you share the order? First one should be a simple update coming when i get a second. The second one is interesting but I am guessing I know the reason.

**Comment by josephwb** [comment]
Trogoniformes (Aves).

**Comment by blackrim** [comment]
Thanks. Will do it now

**Comment by blackrim** [comment]
Git it fixed here dfe1e4aef62bd857a4a1a186fef66029cad06399

**Comment by josephwb** [comment]
Hmm this has started to appear again. Easy fix on my end (delete first and last bracket), but is the catch being bypassed?

**Comment by blackrim** [comment]
Hmm, ok need to check this. I am running pyphlawd too so can do some checks
but do you have a simple example I can run?

**Comment by josephwb** [comment]
The same example above Trogoniformes (Aves) is showing this behaviour.

**Comment by blackrim** [comment]
I am not getting that behavior with Trogoniformes. Just to be clear, it is that you are getting different numbers of taxa when you find_good_clusters at Trogonidae_56309 vs Trogoniformes_56308/Trogonidae_56309/?

**Comment by josephwb** [comment]
Whoops. Sorry I meant the issue is that the constraint tree for the Order has extra brackets (a root edge). The clusters are fine. ( -_・)

**Comment by josephwb** [comment]
Working.
