### ISSUE TITLE
About function

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/PyPHLAWD#17]
Might be nice to have an `about` (or `get_info`) function that describes a db. Information would include:

1. date created
2. ncbi release
3. root taxon
4. number terminal taxa
5. other stuff

Just a thought. Feel free to disregard.

**Comment by Cactusolo** [comment]
aye! 👍 
I usually put "ncbi release" or the date of visit in my publication!

**Comment by blackrim** [comment]
Yes, this is intended to go with the run.html that i am working on with issue https://github.com/FePhyFoFum/PyPHLAWD/issues/16
