### ISSUE TITLE
Location of logfile

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/PyPHLAWD#18]
Could the logfile `log.md.gz` be written to the output directory by default? I have scripts which run things concurrently, but if launched from the same directory they write to the same file. Same goes for `mafft.out` (although this is a temp file, pyphlawd complains when trying to delete it if already deleted by another process).

**Comment by josephwb** [comment]
Yerp, that was the idea.

**Comment by blackrim** [comment]
alright. i can work on that.

**Comment by josephwb** [comment]
I don't know how often people will run things concurrently (although I could add some code to facilitate this) so it might just be me. Not a big deal.
