### ISSUE TITLE
find_good_clusters_for_concat should have extra args

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/PyPHLAWD#23]
It has become abundantly clear that a global `conf.py` does not work for every clade. Specifically:
```
smallest_cluster
cluster_prop
```
Presently `find_good_clusters_for_concat.py` just uses the values from `conf.py`. It is a bit of a pain to edit the latter while troubleshooting. It would be nice if the former used these values by default but could be overridden by optional args. This should be easy with the switch to argparse (#14).

**Comment by Cactusolo** [comment]
@josephwb I see two options are added:
# usage: find_good_clusters_for_concat.py -d DIR -b DATABASE [-i]
#-d : define where is path to your cluster data generated by `setup_clade.py`
#-b the path leading to your plantDB

now the gif in [the tutorial](https://fephyfofum.github.io/PyPHLAWD/other/) and [here](https://fephyfofum.github.io/PyPHLAWD/runs/clustering_ex/) need to be updated.

thanks!

Miao

**Comment by josephwb** [comment]
Much of this has been resolved with https://github.com/FePhyFoFum/PyPHLAWD/commit/bdedfe784f410f31d5ad65a6721a0b54609fecc0 to have better defaults. It would still be nice to provide custom parameters for weirdo. I can do this if it proves to be useful.
