### ISSUE TITLE
Migrate to Python 3

### ISSUE THREAD

**Issue by jamie-arcc** [FePhyFoFum/PyPHLAWD#28]
Python 2 is in its twilight phase now, and more and more everything is moving to Python 3.  For posterity's sake, it would be good if PyPHLAWD made the move as well.  This should be relatively simple, as most, if not all of the python code should be automatically translatable using `2to3`

**Comment by blackrim** [comment]
good point. will be moving to 3 in the next day or so

**Comment by blackrim** [comment]
should be done here 4001fdb14a6a86ff2327bbf4e880c132a578e9cc
basic functions work but will continue testing.
