### ISSUE TITLE
missing variable in find_good_clusters_for_concat.py

### ISSUE THREAD

**Issue by dbenesh82** [FePhyFoFum/PyPHLAWD#30]
Hi there,
I cloned the repo this week to try and build a large tapeworm phylogeny. When I ran the find_good_clusters script I got the error that the 'py' variable was undefined. To remedy, I just added "from conf import py" to the beginning of the script.

**Comment by blackrim** [comment]
aha! good catch. this came with the transition to python3 
e521031
