### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by Raif-fl** [FePhyFoFum/PyPHLAWD#35]
I am getting the following traceback error while trying to run the baited example. 

MAKING TREE Adoxaceae
Traceback (most recent call last):
File "Desktop/PyPHLAWD/src/get_ncbi_tax_tree_no_species.py", line 97, in <module>
 tree = construct_tree(taxon, DB, taxalist)
 File "Desktop/PyPHLAWD/src/get_ncbi_tax_tree_no_species.py", line 53, in construct_tree
    c.execute("select ncbi_id from taxonomy where name = ? and node_rank != 'species'", (taxon, ))
sqlite3.OperationalError: no such table: taxonomy
Traceback (most recent call last):
  File "../../src/setup_clade_bait.py", line 39, in <module>
    trn = tree_reader.read_tree_file_iter(tname).__next__().label
StopIteration

I cannot figure out which file exactly is causing the problem.

**Comment by Cactusolo** [comment]
What is your execute cmd?

Have you download/build the “plnDB.db" database? Have you installed all the requirements? 

Are all the python scripts in the same directory?

I think more information needed to diagnose.

Miao

*********************************

Dr. Miao Sun

Post-Doc Associate
Plant Evolution and Biodiversity (PEB) Group
Department of Bioscience - Ecoinformatics and Biodiversity
Aarhus University
Denmark

Email: miaosun@bios.au.dk
Website: www.sunmiao.name
Twitter: @Miao_the_Sun
