### ISSUE TITLE
PROBLEM REDOING ALIGNMENT

### ISSUE THREAD

**Issue by szhan** [FePhyFoFum/PyPHLAWD#36]
Hi!

I keep encountering "PROBLEM REDOING ALIGNMENT" when performing either the cluster or baited analysis. MAFFT is root installed and all the dependencies have been exported in PATH.

When doing a baited analysis to get Adoxaceae sequences, the info.csv contains:
"species,rbcL.fa
Viburnum kansuense,x
Viburnum erosum,x
..."

I also get problem_subMSAtable and problem_temp.mergealn. It is the same when doing a cluster analysis.

I suspected that it may be pycat, but it is clearly in PATH (I can see it when echo $PATH). I am not really getting an output overall. I would appreciate any insight to troubleshoot this issue.

Thank you very much,
Shing

**Comment by blackrim** [comment]
That is typically the case when there are issues with the rate of evolution. If it is quite fast or if there are issues with sequences this can be a cause. The other can be an out of date mafft. I would recommend updating mafft and trying again.
