### ISSUE TITLE
cnode 

### ISSUE THREAD

**Issue by listona** [FePhyFoFum/PyPHLAWD#8]
Any suggestions for the following error?  
Traceback (most recent call last):
  File "../programs/PyPHLAWD/src/setup_clade.py", line 3, in <module>
    import tree_reader
  File "/home/listona/programs/PyPHLAWD/src/tree_reader.py", line 4, in <module>
    from cnode import Node
ImportError: No module named cnode

**Comment by blackrim** [comment]
You should be able to run `bash compile_cython.sh` in the `src` directory. If that doesn't work, you can replace the references to `import cnode` to `import node`. I will up this so that you can change that in the `conf.py` or so that it will auto detect.

**Comment by listona** [comment]
I will give this a try – thanks!

**Comment by blackrim** [comment]
Yes and please let me know if you run into issues. Generally things are tested on mac and linux but mac continues to be a challenge as they change some libraries every release. So things may be a bit behind if you are on Mac.

**Comment by dportik** [comment]
Had the same issue but ran bash compile_cython.sh in the src directory and now it is working fine.
