### ISSUE TITLE
Missing stuff docs

### ISSUE THREAD

**Issue by josephwb** [FePhyFoFum/PyPHLAWD#9]
This gets it done for me on linux:
```
sudo pip install cython
```
So, easy, but just not expected until the error surfaces when trying to execute things.

**Comment by josephwb** [comment]
This seems to be missing as well:
```
sudo pip install networkx
```

**Comment by jfwalker** [comment]
Some of the programs in phyx are dependencies and should probably be added as well: pxssort, pxrevcomp, pxrmt, pxcat, pxrms

**Comment by josephwb** [comment]
Just adding stuff here as it arises.

I installed fasttree using:
```
sudo spt-get installk fasttree
```
pyphlawd expects an uppercase `Fasttree` (installed from source, I imagine). This is remedied by putting this in `.bashrc`:
```
alias Fasttree=fasttree
```

**Comment by blackrim** [comment]
I believe this is done.
